config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get 'about' => 'static#about'
  get 'contacts' => 'static#contacts'
  get 'presentation' => 'static#presentation'

  devise_for :users, path: 'profile', path_names: {
                       sign_in: 'login',
                       sign_out: 'logout',
                       password: 'secret',
                       confirmation: 'verification',
                       unlock: 'unblock',
                       registration: 'register',
                       sign_up: 'registration'
                   }, :controllers => { :omniauth_callbacks => 'callbacks' }

  resource  :profile, only: [:show, :edit, :update]
  post '/profile', to: 'profiles#delete_userpic'
  resources :users, only: [:index, :show]

  resources :categories, only: [:index, :show], param: :slug
  resources :tags, only: [:index, :show]

  resources :achievements,  only: [:index, :show, :edit, :update]
  resources :medals,        only: [:index, :show, :update]
  resources :challenges

  resources :users, only: [:index, :show] do
    resources :achievements,
              controller: 'users/achievements',
              only: [:index, :show]
    resources :medals,
              controller: 'users/medals',
              only: [:index, :show]
    resources :challenges,
              controller: 'users/challenges',
              only: [:index, :show]
  end

  get 'dashboard' => 'dashboard#index'
    namespace :dashboard do

      resources :categories
      resources :tags

      resources :achievements

      resources :medals

      resources :challenges

      resources :users

    end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :omniauthable, :omniauth_providers => [:github, :facebook, :twitter, :vkontakte]


  #validations
  validates :email, uniqueness: true
  validates :name, presence: { message: 'Can`t be blank' }
  validates :name, length: {
                      minimum: 3,
                      maximum: 128,
                      too_short: 'Name is too short...',
                      too_long:  'Name is too long...'
                  }
  validates :city, :social_link_fb, :social_link_tw, :social_link_vk, :social_link_inst, length: {
                     maximum: 128,
                     too_long:  'Sorry, too much symbols...'
                 }

  #relations

  #Achievements
  has_many :user_achieveds
  has_many :achievements, through: :user_achieveds

  #Medals
  has_many :user_medaleds
  has_many :medals, through: :user_medaleds


  #userpic
  has_attached_file :userpic,
                    styles: {
                        large:      ['x750>', :jpg],
                        medium:     ['x500>', :jpg],
                        small:      ['250x250#', :jpg],
                        thumb:      ['100x100#', :jpg]
                    },
                    convert_options: { all: '-quality 70' },
                    default_url: '/images/userpic.svg'
  validates_attachment_content_type :userpic, content_type: /\Aimage\/.*\Z/


  #OmniAuth
  def self.from_omniauth(auth)

    @member = self.find_by email: auth.info.email

    if @member.nil?

      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.email = (auth.info.email.nil? || auth.info.email == 'null' ? "#{SecureRandom.hex(8)}@progressbook.me" : auth.info.email)
        user.password = Devise.friendly_token[0,20]
        user.userpic = auth.info.image
      end

    else

      @member.provider = auth.provider
      @member.uid = auth.uid
      if @member.userpic_file_name.nil?
        @member.userpic = auth.info.image
      end
      @member.save

      return @member

    end

  end

  #country codes to names
  def country_name
    c = ISO3166::Country[country]
    c.translations[I18n.locale.to_s] || c.name
  end




end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  include Dashboard

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users/achievements_controller.rb
class Users::AchievementsController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @achievements = @user.achievements
                    .joins(:user_achieveds).distinct
                    .order('user_achieveds.created_at DESC')
                    .page params[:page]
  end

  def show
    @user = User.find params[:user_id]
    @achievement = @user.achievements.find params[:id]
  end
end

app/controllers/users/challenges_controller.rb
class Users::ChallengesController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @challenges = @user.challenges.page params[:page]
  end

  def show
    @user = User.find params[:user_id]
    @challenge = @user.challenges.find params[:id]
  end
end

app/controllers/users/medals_controller.rb
class Users::MedalsController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @medals = @user.medals
                    .joins(:user_medaleds).distinct
                    .order('user_medaleds.created_at DESC')
                    .page params[:page]
  end

  def show
    @user = User.find params[:user_id]
    @medal = @user.medals.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'no_sidebar', only: :index

  def index
    @users = User.all.order( 'current_sign_in_at DESC' ).page params[:page]
  end

  def show
    @user = User.find params[:id]
  end

end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/users/achievements_helper.rb
module Users::AchievementsHelper

  # TODO: get from user achievs @achievements
  def achieved_date user, ach
    date = UserAchieved.find_by(user_id: user.id, achievement_id: ach.id).created_at
    date.strftime("%B %-d %Y, %H:%M")
  end

  def proof
    proof = UserAchieved.find_by(user_id: @user.id, achievement_id: @achievement.id )
  end

end

app/helpers/users/challenges_helper.rb
module Users::ChallengesHelper
end

app/helpers/users/medals_helper.rb
module Users::MedalsHelper

  # TODO: get from user medals @medals
  def medaled_date user, med
    date = UserMedaled.find_by(user_id: user.id, medal_id: med.id).created_at
    date.strftime("%B %-d %Y, %H:%M")
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_medals(usr)
    UserMedaled.where(user_id: usr.id).order(created_at: :desc).limit(16)
  end


  def user_achievments(usr)
    UserAchieved.where(user_id: usr.id).order(created_at: :desc).limit(32)
  end


  def user_challenges(usr)
  end

end

app/views/users/_list.html.erb
<div class="users">
<% @users.each do |user| %>
  <div class="user-card">
    <div class="card-panel">
      <div class="row">
        <div class="col s4">
          <%=
            link_to(user_path(user.id)) do
              image_tag user.userpic.url(:thumb), alt: '', class: 'circle responsive-img'
            end
          %>
        </div>
        <div class="col s8">
          <h5><%= user.name %></h5>
          <%= link_to 'Open profile',
              user_path(user.id),
              class: 'waves-effect waves-light btn'
          %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/users/index.html.erb
<h3>All Users</h3>
<%= render partial: 'list' %>
<p><%= paginate @users %></p>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>
<ul class="collection">
  <% if @user.date_of_birth? %>
  <li class="collection-item">
    <b>Birthday:</b> <%= @user.date_of_birth.strftime('%d.%m.%Y') %>,
    (Age: <%= ((Time.now - @user.date_of_birth.to_time)/1.year).to_i %>)
  </li>
  <% end %>

  <% if @user.gender? && @user.gender != 'gender' %>
  <li class="collection-item"><b>Gender:</b> <%= @user.gender %></li>
  <% end %>

  <% if @user.country? || @user.city? %>
  <li class="collection-item">
    <b>Location:</b> <%= @user.country? ? (@user.country_name) : '' %> <%= @user.city? ? @user.city : '' %>
  </li>
  <% end %>

  <% if @user.bio? %>
  <li class="collection-item">
    <b>About:</b><br>
    <%= @user.bio %>
  </li>
  <% end %>

</ul>

<h4>Medals (<%= link_to user_medals(@user).count, user_medals_path(@user.id) %>)</h4>
<p>
<% user_medals(@user).each do |m| %>
  <%= link_to (image_tag m.medal.medal_icon.url(:thumb)),
      user_medal_path(@user.id, m.medal.id)
  %>
<% end %>
</p>

<h4>Achievements (<%= link_to user_achievments(@user).count, user_achievements_path(@user.id) %>)</h4>
<p>
<% user_achievments(@user).each do |a| %>
  <%= link_to (image_tag a.achievement.achievement_icon.url(:thumb)),
      user_achievement_path(@user.id, a.achievement.id)
  %>
<% end %>
</p>

<h4>Challenges</h4>
<p>// Challenges here</p>