config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get 'about' => 'static#about'
  get 'contacts' => 'static#contacts'
  get 'presentation' => 'static#presentation'

  devise_for :users, path: 'profile', path_names: {
                       sign_in: 'login',
                       sign_out: 'logout',
                       password: 'secret',
                       confirmation: 'verification',
                       unlock: 'unblock',
                       registration: 'register',
                       sign_up: 'registration'
                   }, :controllers => { :omniauth_callbacks => 'callbacks' }

  resource  :profile, only: [:show, :edit, :update]
  post '/profile', to: 'profiles#delete_userpic'
  resources :users, only: [:index, :show]

  resources :categories, only: [:index, :show], param: :slug
  resources :tags, only: [:index, :show]

  resources :achievements,  only: [:index, :show, :edit, :update]
  resources :medals,        only: [:index, :show, :update]
  resources :challenges

  resources :users, only: [:index, :show] do
    resources :achievements,
              controller: 'users/achievements',
              only: [:index, :show]
    resources :medals,
              controller: 'users/medals',
              only: [:index, :show]
    resources :challenges,
              controller: 'users/challenges',
              only: [:index, :show]
  end

  get 'dashboard' => 'dashboard#index'
    namespace :dashboard do

      resources :categories
      resources :tags

      resources :achievements

      resources :medals

      resources :challenges

      resources :users

    end

end

app/views/shared/_aside.html.erb
<% if user_signed_in? %>

    <%= render partial: 'shared/aside_user' %>

<% else  %>

    <%= render template: 'devise/sessions/new' %>

<% end %>

app/views/shared/_aside_cats_tags.html.erb
<% if user_signed_in? %>
<div class="small-user-card">
  <div class="card-panel">
    <div class="row">
      <div class="col s4">
        <%=
          link_to(user_path(@user.id)) do
            image_tag @user.userpic.url(:thumb), alt: '', class: 'circle responsive-img'
          end
        %>
      </div>
      <div class="col s8">
        <h5><%= link_to @user.name, user_path(@user.id) %></h5>
      </div>
    </div>
  </div>
</div>
<% end %>
<h5 class="cats-tags">Categories</h5>
<div class="categories collection">
  <%= link_to 'All', "/#{params[:controller]}", class: 'collection-item' %>
  <% @cats.each do |cat| %>
    <%= link_to cat.title, "/#{params[:controller]}?cat=#{cat.id}", class: 'collection-item' %>
  <% end %>
</div>

<% unless params[:controller] == 'challenges' %>
<h5 class="cats-tags">Popular Tags</h5>
<div class="tags">
  <% @tags.each do |tag| %>
  <div class="chip">
    <%= link_to tag.name, "/#{params[:controller]}?tag=#{tag.id}" %>
  </div>
  <% end %>
</div>
<div class="divider"></div>
<%= link_to 'All tags', '#' %>
<% end %>

app/views/shared/_aside_user.html.erb
<div class="card">
  <div class="card-image">
    <%= image_tag @user.userpic.url(:medium) %>
  </div>
  <div class="card-content">
    <span class="card-title"><%= link_to @user.name, user_path(@user.id) %></span>
    <p>
      <% if @user.social_link_fb? %>
      <%= link_to '', @user.social_link_fb, target: '_blank',
                  class: 'socbutton socicon socicon-facebook'
      %>
      <% end %>

      <% if @user.social_link_vk? %>
          <%= link_to '', @user.social_link_vk, target: '_blank',
                      class: 'socbutton socicon socicon-vkontakte'
          %>
      <% end %>

      <% if @user.social_link_tw? %>
          <%= link_to '', @user.social_link_tw, target: '_blank',
                      class: 'socbutton socicon socicon-twitter'
          %>
      <% end %>

      <% if @user.social_link_inst? %>
          <%= link_to '', @user.social_link_inst, target: '_blank',
                      class: 'socbutton socicon socicon-instagram'
          %>
      <% end %>

    </p>
  </div>
  <% if current_user.id == @user.id %>
  <div class="card-action edit-login-buttons">
    <%= link_to ('<i class="material-icons">create</i>'.html_safe),
                edit_profile_path,
                class: 'edit-profile tooltipped not-link',
                data: {position: 'bottom', delay: '50', tooltip: 'Edit profile'}
    %>
    <%= link_to ('<i class="material-icons">exit_to_app</i>').html_safe,
                :destroy_user_session,
                method: 'delete',
                class: 'logout-profile tooltipped not-link',
                data: {position: 'bottom', delay: '50', tooltip: 'Logout'}
    %>
  </div>
  <% end %>
</div>


<div>

</div>

app/views/shared/_footer.html.erb
<footer class="page-footer">
    <div class="row container">
      <div class="col l6 s12">
        <h5 class="white-text">Footer Content</h5>
        <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
        </ul>
      </div>
    </div>
  <div class="footer-copyright">
    <div class="container">
      © 2016 ProgressBook
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<head>
  <title>ProgressBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
  <link rel="manifest" href="/favicon/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  <!-- Facebook -->
  <meta property="og:url"           content="http://progressbook.me" />
	<meta property="og:type"          content="website" />
	<meta property="og:title"         content="ProgressBook" />
	<meta property="og:description"   content="Achievements for your life" />
	<meta property="og:image"         content="/images/social-cover.png" />

  <!-- Twitter -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="@site_username">
  <meta name="twitter:title" content="Top 10 Things Ever">
  <meta name="twitter:description" content="Up than 200 characters.">
  <meta name="twitter:creator" content="@creator_username">
  <meta name="twitter:image:src" content="/images/social-cover.png">
  <meta name="twitter:domain" content="progressbook.me">

  <!-- Vk and global -->
  <meta name="title" content="Заголовок статьи" />
  <meta name="description" content="" />
  <link rel="image_src" href="/images/social-cover.png" />

</head>

app/views/shared/_header.html.erb
<header>

  <nav>
    <div class="nav-wrapper container">
      <%= link_to ('<i class="material-icons left">timeline</i> ProgressBook').html_safe,
          root_path,
          class: 'brand-logo'
      %>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to 'Achievements', achievements_path %></li>
        <li><%= link_to 'Medals', medals_path %></li>
        <li><%= link_to 'Challenges', challenges_path %></li>
      </ul>
    </div>
  </nav>

</header>

app/views/shared/_notices.html.erb
<div class="flash-message">
  <% flash.each do |name, msg| -%>
      <div class="card-panel system-message <%= name %>">
        <span class="white-text"><%= msg %></span>
        <i class="material-icons white-text close-this">close</i>
      </div>
  <% end -%>
</div>