config/routes.rb
Rails.application.routes.draw do

  root 'static#home'
  get 'about' => 'static#about'
  get 'contacts' => 'static#contacts'
  get 'presentation' => 'static#presentation'

  devise_for :users, path: 'profile', path_names: {
                       sign_in: 'login',
                       sign_out: 'logout',
                       password: 'secret',
                       confirmation: 'verification',
                       unlock: 'unblock',
                       registration: 'register',
                       sign_up: 'registration'
                   }, :controllers => { :omniauth_callbacks => 'callbacks' }

  resource  :profile, only: [:show, :edit, :update]
  post '/profile', to: 'profiles#delete_userpic'
  resources :users, only: [:index, :show]

  resources :categories, only: [:index, :show], param: :slug
  resources :tags, only: [:index, :show]

  resources :achievements,  only: [:index, :show, :edit, :update]
  resources :medals,        only: [:index, :show, :update]
  resources :challenges

  resources :users, only: [:index, :show] do
    resources :achievements,
              controller: 'users/achievements',
              only: [:index, :show]
    resources :medals,
              controller: 'users/medals',
              only: [:index, :show]
    resources :challenges,
              controller: 'users/challenges',
              only: [:index, :show]
  end

  get 'dashboard' => 'dashboard#index'
    namespace :dashboard do

      resources :categories
      resources :tags

      resources :achievements

      resources :medals

      resources :challenges

      resources :users

    end

end

app/models/medal.rb
class Medal < ActiveRecord::Base

  #validates
  validates :title, :slug, :description, :medal_icon,
            presence: { message: 'Sorry, can`t be blank' }
  validates :category_ids, :achievement_ids,
            presence: { message: 'Category and Achievements can`t be blank' }

  #relations
  has_many :user_medaleds, dependent: :destroy
  has_many :users, through: :user_medaleds, dependent: :destroy
  has_and_belongs_to_many :achievements, dependent: :destroy
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :tags

  #image
  has_attached_file :medal_icon,
                    styles: {
                        giant:  '750x750>',
                        large:  '500x500>',
                        medium: '250x250>',
                        thumb:  '100x100>',
                        small:  '50x50>'
                    },
                    default_url: '/images/default.png'
  validates_attachment_content_type :medal_icon, content_type: /\Aimage\/.*\Z/

end

app/controllers/concerns/dashboard.rb
module Dashboard

  extend ActiveSupport::Concern

  included do

    layout 'dashboard'
    before_action  :check_admin,:authenticate_user!

  end

end

app/controllers/dashboard/achievements_controller.rb
class Dashboard::AchievementsController < ApplicationController

  include Dashboard

  def index
    @achievements = Achievement.all.order(id: :desc).page params[:page]
  end

  def show
    @achievement = Achievement.find params[:id]
  end

  def new
    @achievement = Achievement.new
    @categories = Category.all
    @tags = Tag.all
  end

  def create
    @categories = Category.all
    @tags = Tag.all
    @achievement = Achievement.new achievement_params

    if @achievement.save
      flash[:notice] = 'Achievement created'
      redirect_to dashboard_achievements_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new Achievement'
      render :action => :new
    end
  end

  def edit
    @achievement = Achievement.find params[:id]
    @categories = Category.all
    @tags = Tag.all
  end

  def update
    @achievement = Achievement.find params[:id]

    if @achievement.update_attributes achievement_params
      flash[:notice] = 'Achievement has been updated'
      redirect_to dashboard_achievements_path
    else
      flash.now[:warning] = 'There were problems when trying to update this achievement'
      render :action => :show
    end
  end

  def destroy
    @achievement = Achievement.find params[:id]

    @achievement.destroy
    flash[:notice] = 'Achievement has been deleted'
    redirect_to dashboard_achievements_path
  end

  private
  def achievement_params
    params.require(:achievement).permit(
                                  :title,
                                  :slug,
                                  :description,
                                  :achievement_icon,
                                  :achievement_icon_file_name,
                                  { category_ids:[] },
                                  { tag_ids:[] }
                                  )
  end

end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController

  include Dashboard

  def index
    @categories = Category.all.page params[:page]
    @category = Category.new
  end

  def show
    @category = Category.find params[:id]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      flash[:notice] = 'Category created'
      redirect_to dashboard_categories_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new category'
      render :action => :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]

    if @category.update_attributes category_params
      flash[:notice] = 'Category has been updated'
      redirect_to dashboard_categories_path
    else
      flash.now[:warning] = 'There were problems when trying to update this category'
      render :action => :show
    end
  end

  def destroy
    @category = Category.find params[:id]

    @category.destroy
    flash[:notice] = 'Category has been deleted'
    redirect_to dashboard_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :slug, :description, :category_icon, :category_icon_file_name)
  end

end

app/controllers/dashboard/challenges_controller.rb
class Dashboard::ChallengesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/dashboard/medals_controller.rb
class Dashboard::MedalsController < ApplicationController

  include Dashboard

  def index
    @medals = Medal.all.page params[:page]
  end

  def show
    @medal = Medal.find params[:id]
  end

  def new
    @medal = Medal.new
    @achievements = Achievement.all
    @categories = Category.all
    @tags = Tag.all
  end

  def create
    @medal = Medal.new medal_params

    if @medal.save
      flash[:notice] = 'Medal created'
      redirect_to dashboard_medals_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new Medal'
      render :action => :new
    end
  end

  def edit
    @medal = Medal.find params[:id]
    @achievements = Achievement.all
    @categories = Category.all
    @tags = Tag.all
  end

  def update
    @medal = Medal.find params[:id]

    if @medal.update_attributes medal_params
      flash[:notice] = 'medal has been updated'
      redirect_to dashboard_medals_path
    else
      flash.now[:warning] = 'There were problems when trying to update this Medal'
      render :action => :show
    end
  end

  def destroy
    @medal = Medal.find params[:id]

    @medal.destroy
    flash[:notice] = 'Achievement has been deleted'
    redirect_to dashboard_medals_path
  end

  private
  def medal_params
    params.require(:medal).permit(
        :title,
        :slug,
        :description,
        :medal_icon,
        :medal_icon_file_name,
        { achievement_ids:[] },
        { category_ids:[] },
        { tag_ids:[] }
    )
  end
end

app/controllers/dashboard/tags_controller.rb
class Dashboard::TagsController < ApplicationController

  include Dashboard

  def index
    @tags = Tag.all #.paginate(:page => params[:page], :per_page => 20)
    @tag  = Tag.new
  end

  def show
    @tag = Tag.find params[:id]
  end

  def new
    @tag  = Tag.new
  end

  def create
    @tag  = Tag.new tag_params
    if @tag.save
      flash[:notice] = 'Tag created'
      redirect_to dashboard_tags_path
    else
      flash.now[:warning] = 'There were problems when trying to create a new tag'
      render :action => :new
    end

  end

  def edit
    @tag = Tag.find params[:id]
  end

  def update
    @tag = Tag.find params[:id]
    if @tag.update_attributes tag_params
      flash[:notice] = 'Tag has been updated'
      redirect_to dashboard_tags_path
    else
      flash.now[:warning] = 'There were problems when trying to update this tag'
      render :action => :show
    end
  end

  def destroy
    @tag = Tag.find params[:id]

    @tag.destroy
    flash[:notice] = 'Tag has been deleted'
    redirect_to dashboard_tags_path
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :description)
  end

end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController

  include Dashboard

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  include Dashboard

  def index

  end
end

app/controllers/medals_controller.rb
class MedalsController < ApplicationController

  before_action :authenticate_user!, only: [:edit, :update]
  layout 'no_sidebar', except: :index

  def index

    @user = current_user

    @cats = Category.all
    @tags = Tag.select("tags.*, COUNT(medals.id) medals_count")
      .joins(:medals)
      .group("tags.id")
      .order("medals_count DESC")
      .limit(24)
    @all_tags = Tag.all


    # TODO: not good... do refactor!
    cat_id = params[:cat]
    tag_id = params[:tag]

    if @cats.exists? cat_id

      @medals = Category.find(cat_id)
        .medals
        .order(id: :desc)
        .page params[:page]

      @cat_id_title = Category.find(cat_id).title

    elsif @all_tags.exists? tag_id

      @medals = Tag.find(tag_id)
        .medals
        .order(id: :desc)
        .page params[:page]
      @cat_id_title = Tag.find(tag_id).name

    else

      @medals = Medal.all
        .order(id: :desc)
        .page params[:page]
      @cat_id_title = ''
      @tag_id_title = ''

    end
    # not good end



    render layout: 'cats_tags'

  end

  def show

    @user = current_user
    @medal = Medal.find params[:id]

  end

  def update

    @user = current_user
    @medal = Medal.find params[:id]

    achievements_count = Achievement.joins(:medals, :users)
                                    .where('medal_id = ? AND user_id = ?', @medal.id, @user.id )
                                    .count

    if achievements_count == @medal.achievements.count
      @medaled = UserMedaled.where(user_id: @user.id, medal_id: @medal.id).first_or_initialize
      unless @medaled.save
        flash[:warning] = 'Sorry, problem... Try again later'
        redirect_to medal_path(@medal.id)
      end
    else
      redirect_to medal_path(@medal.id)
    end
  end

end

app/controllers/users/medals_controller.rb
class Users::MedalsController < ApplicationController
  def index
    @user = User.find params[:user_id]
    @medals = @user.medals
                    .joins(:user_medaleds).distinct
                    .order('user_medaleds.created_at DESC')
                    .page params[:page]
  end

  def show
    @user = User.find params[:user_id]
    @medal = @user.medals.find params[:id]
  end
end

app/helpers/dashboard/achievements_helper.rb
module Dashboard::AchievementsHelper
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/challenges_helper.rb
module Dashboard::ChallengesHelper
end

app/helpers/dashboard/medals_helper.rb
module Dashboard::MedalsHelper
end

app/helpers/dashboard/tags_helper.rb
module Dashboard::TagsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/medals_helper.rb
module MedalsHelper

  def achievements_count medal, user
    Achievement.joins(:medals, :users)
               .where('medal_id = ? AND user_id = ?', medal, user )
               .count
  end

  def medal_user_percent medal, user
    all  = medal.achievements.count
    #TODO: DRY!
    part = Achievement.joins(:medals, :users)
                      .where('medal_id = ? AND user_id = ?', medal, user )
                      .count
    "#{(part.to_f / all.to_f * 100.0).to_i}%"
  end

  # for single medal (show)
  def medal_percent(medal)
    all  = User.all.count
    part = UserMedaled.where(medal_id: medal.id).count
    "#{(part.to_f / all.to_f * 100.0).to_i}%"
  end

  def medal_last_twelve(medal)
    UserMedaled.where(medal_id: medal.id).order(created_at: :desc).limit(12)
  end

  def medal_and_more(medal)
    more = UserMedaled.where(medal_id: medal.id).count - 12

    if more > 9999
      ('<div class="and_more tooltipped" data-tooltip="more users">+9999</div>').html_safe
    elsif more < 1
      ''
    else
      ("<div class=\"and_more tooltipped\" data-tooltip=\"more users\">+#{more}</div>").html_safe
    end

  end

end

app/helpers/users/medals_helper.rb
module Users::MedalsHelper

  # TODO: get from user medals @medals
  def medaled_date user, med
    date = UserMedaled.find_by(user_id: user.id, medal_id: med.id).created_at
    date.strftime("%B %-d %Y, %H:%M")
  end

end

app/views/dashboard/medals/_form.html.erb
<div class="row medal-form">
<%= simple_form_for [:dashboard, @medal] do |f| %>

<div class="col s12 m8 l8">

  <div class="input-field">
    <%= f.input :title, label: 'Title' %>
  </div>

  <div class="input-field">
      <%= f.input :slug, label: 'Slug' %>
  </div>

  <div class="input-field">
      <%= f.input :description,
                  label: 'Description',
                  as: :text,
                  required: false,
                  input_html: { class: 'materialize-textarea' }
      %>
  </div>

  <div class="file-field input-field">
      <div class="btn">
          <span>Medal Icon</span>
          <%= f.input :medal_icon, as: :file, label: false %>
      </div>
      <div class="file-path-wrapper">
          <input class="file-path" type="text">
      </div>
  </div>

  <ul class="tabs">
    <li class="tab"><a class="active" href="#achs">Achievements</a></li>
    <li class="tab"><a href="#tags">Tags</a></li>
  </ul>

  <div class="tabs-content">

    <div class="achievementslist" id="achs">
      <input type="hidden" name="medal[achievement_ids][]" value="">
      <ul class="collapsible" data-collapsible="expandable">
        <% @categories.each do |cat| %>
        <li>
          <div class="collapsible-header"><%= image_tag cat.category_icon.url(:small) %> <%= cat.title %></div>
          <div class="collapsible-body row">
            <% cat.achievements.order(id: :desc).each do |ach| %>

              <div class="col s3 m3 l3">
                <div class="card">
                  <div class="card-image">
                    <%= image_tag ach.achievement_icon.url(:medium) %>
                    <span class="card-title"><%= ach.title %></span>
                  </div>
                  <div class="card-action">
                    <%= check_box_tag 'medal[achievement_ids][]',
                                      ach.id,
                                      @medal.achievements.include?(ach),
                                      class: 'filled-in',
                                      id: "medal_achievement_ids_#{ach.id}_#{cat.id}"
                    %>
                    <label for="medal_achievement_ids_<%= ach.id %>_<%= cat.id %>">
                      <%= ach.title %>
                    </label>
                  </div>
                </div>
              </div>

            <% end %>

          </div>

        </li>
        <% end %>
      </ul>

    </div>

    <div class="taglist" id="tags">
      <input type="hidden" name="medal[tag_ids][]" value="">
      <% @tags.each do |tag| %>
      <div class="chip">
        <%= check_box_tag 'medal[tag_ids][]',
                          tag.id,
                          @medal.tags.include?(tag),
                          class: 'filled-in',
                          id: "medal_tag_ids_#{tag.id}"
        %>
        <label for="medal_tag_ids_<%= tag.id %>">
          <%= tag.name %>
        </label>
      </div>
      <% end %>
    </div>

  </div>

</div>
<%
 # TODO: to forms wrapper. Use association
%>

<div class="col s12 m4 l4 categorylist">

  <input type="hidden" name="medal[category_ids][]" value="">
  <ul class="collection">
  <% @categories.each do |category| %>
    <li class="collection-item avatar">
      <%= image_tag category.category_icon.url(:small), alt: '', class: 'circle' %>
    <span class="title">
      <%= check_box_tag 'medal[category_ids][]',
                        category.id,
                        @medal.categories.include?(category),
                        id: "medal_category_ids_#{category.id}"
      %>
      <label for="medal_category_ids_<%= category.id %>">
        <%= category.title %>
      </label>
    </span>
    <p><%= category.description %></p>
    </li>
  <% end %>
  </ul>

</div>

<div class="col s12 m12 l12 ok">
  <%= f.button :submit %>
  <%= link_to 'Cancel', dashboard_medals_path, class: 'cancel' %>
</div>
<% end %>
</div>

app/views/dashboard/medals/_list.html.erb
<table>
  <thead>
  <tr>
    <th>Image</th>
    <th>Title</th>
    <th>Slug</th>
    <th>Description</th>
    <th>&nbsp;</th>
  </tr>
  </thead>

  <% @medals.each do |medal| %>
      <tr>
        <td><%= image_tag medal.medal_icon.url(:small) %></td>
        <td><%= medal.title %></td>
        <td><%= medal.slug %></td>
        <td><%= medal.description.html_safe %></td>
        <td>
          <%= link_to 'Show', dashboard_medal_path(medal.id), target: '_blank' %>
          <%= link_to 'Edit',   edit_dashboard_medal_path(medal.id) %>
          <%= link_to 'Delete',
                      dashboard_medal_path(medal.id),
                      method: 'delete',
                      data: { confirm: 'Are you sure?' },
                      class: 'delete'
          %>
        </td>
      </tr>
  <% end %>

</table>

app/views/dashboard/medals/edit.html.erb
<h3>
  <%= @medal.medal_icon? ? (image_tag @medal.medal_icon.url(:small)) : '' %>
  Edit Medal
</h3>
<%= render :partial => 'form' %>

app/views/dashboard/medals/index.html.erb
<h3>Medals</h3>
<%= link_to 'add New', new_dashboard_medal_path %>


<%= render :partial => 'list' %>

<p><%= paginate @medals %></p>

app/views/dashboard/medals/new.html.erb
<h3>Create new Medal</h3>

<%= render :partial => 'form' %>

app/views/dashboard/medals/show.html.erb
<h1>Dashboard::Achievement#show</h1>

<h2>
  <%= @medal.title %>
</h2>
<i><%= @medal.slug %></i>
<p><%= @medal.description %></p>

<div>
  <%= image_tag @medal.medal_icon.url(:medium) %>
</div>